.

diff --git a/.github/workflows/build_wheels.yml b/.github/workflows/build_wheels.yml
--- a/.github/workflows/build_wheels.yml
+++ b/.github/workflows/build_wheels.yml
@@ -20,11 +20,20 @@ jobs:
       CIBW_BUILD: "cp3*-*"
       CIBW_SKIP: "pp* *-musllinux*"
       CIBW_TEST_SKIP: "*"
+      CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
+      CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
       CIBW_BEFORE_ALL_LINUX: |
-        yum install -y yum-utils && \
-        yum-config-manager --set-enabled crb || true && \
-        yum install -y epel-release && \
-        yum install -y boost-devel gsl-devel CGAL-devel
+        if command -v dnf >/dev/null; then
+          dnf install -y 'dnf-command(config-manager)'
+          dnf config-manager --set-enabled crb
+          dnf install -y epel-release
+          dnf install -y boost-devel gsl-devel CGAL-devel
+        else
+          yum install -y epel-release
+          yum-config-manager --enable epel
+          yum install -y boost-devel gsl-devel CGAL-devel || \
+            { echo "CGAL-devel not found on EL7; exit"; exit 1; }
+        fi
       CIBW_BEFORE_ALL_MACOS: >-
         brew update && brew install boost cgal gsl
       CIBW_BEFORE_ALL_WINDOWS: >-
