.

diff --git a/.github/workflows/build_wheels.yml b/.github/workflows/build_wheels.yml
--- a/.github/workflows/build_wheels.yml
+++ b/.github/workflows/build_wheels.yml
@@ -15,7 +15,7 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-22.04, windows-2022, macos-14]
+        os: [ubuntu-22.04]
     env:
       CIBW_BUILD: "cp3*-*"
       CIBW_SKIP: "pp* *-musllinux*"
@@ -28,13 +28,15 @@ jobs:
         if command -v dnf >/dev/null; then
           dnf install -y 'dnf-command(config-manager)'
           dnf config-manager --set-enabled crb
-          dnf install -y epel-release
+          dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
           dnf install -y boost-devel gsl-devel CGAL-devel
         else
-          yum install -y epel-release
+          yum install -y yum-utils
           yum-config-manager --enable epel
-          yum install -y boost-devel gsl-devel CGAL-devel || \
-            { echo "CGAL-devel not found on EL7; exit"; exit 1; }
+          yum install -y epel-release
+          yum install -y boost-devel gsl-devel CGAL-devel || {
+            echo "CGAL-devel not found on EL7; exit"; exit 1;
+          }
         fi
       CIBW_BEFORE_ALL_MACOS: |
           export MACOSX_DEPLOYMENT_TARGET=13.0
